FROM gradle:8.5-jdk17 AS build
WORKDIR /build
COPY . .
RUN gradle :soraAdmin:bootJar

FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=build /build/soraAdmin/build/libs/soraAdmin-0.0.1-SNAPSHOT.jar app.jar
ENTRYPOINT ["java", "-Dspring.profiles.active=docker", "-jar", "app.jar"]
EXPOSE 8080
